### ISSUE TITLE
[Suggestion] DatLoadFile Custom Exporter

### ISSUE THREAD

**Issue by nsiicm0** [Nuix/SuperUtilities#17]
Is it possible to extend the custom exporter and have a function which would get rid of the default columns that will get exported as part of the legal export?

So that we would end up only with the fields that are specified in the Metadataprofile?

**Comment by JuicyDragon** [comment]
Hello @nsiicm0, sorry it took me a bit to get back to you on this, been busy as of late and wasn't sure how extensive the changes would be.  After spending a little time figuring out what needed to be changed I think I have an update in place that supports this rather nicely.  See release [v1.18.0](https://github.com/Nuix/SuperUtilities/releases/tag/v1.18.0) for details and download of compiled JAR.

**Comment by nsiicm0** [comment]
Brilliant, thank you. :-) Exactly what I was looking for. (Sorry for the delay in response, since I paused working on my use case for a while)
