### ISSUE TITLE
Documentation update for 'findAndMarkup'

### ISSUE THREAD

**Issue by cameron-stiller** [Nuix/SuperUtilities#21]
Example provided here:
https://github.com/Nuix/SuperUtilities/blob/master/RubyTests/BulkRedactor.rb

Will error with missing paramater... the paramater missing is the concurrancy... for example:
regions = br.findAndMarkup($currentCase,brs,scope_items,4)

**Comment by JuicyDragon** [comment]
Addressed by commits 59d53312f345e0f5f44b88391b5be25d96db5190 and a7d208ce5b5cfc3111ed675a7e069036568d4cb8

Thanks for reporting this!
